#!/bin/bash

### Output date

log() {
  echo "$@" >&2
}

http_status_line() {
  local status=${1:-500}
  case $status in
    200)
      line='200 OK'
      ;;
    204)
      line='204 No Content'
      ;;
    400)
      line='400 Bad Request'
      ;;
    500)
      line='500 Internal Server Error'
      ;;
    *)
      log "$status is invalid"
      line='500 Internal Server Error'
      ;;
  esac
  printf 'Status:%s\r\n' "$line"
}

http_header() {
  local header=${1:?Specify Header Name}
  local value=${2:?Specify Header Value}
  # TODO escape unsafe characters
  printf '%s:%s\r\n' "$header" "$value"
}

http_separator() {
  printf '\r\n'
}

http_status_line 200
http_header 'Content-Type' 'text/plain'
http_separator

date
