#!/bin/bash

### Output speech synthesized AWS Polly.
###
### @param text - Text which is synthesized to speech
###

text=${1:?Specify a text}

temp=$(mktemp tmp.mp3.XXXXXX)
trap "rm -f '$temp'" EXIT;

## Synthesize text to speech
aws polly synthesize-speech --output-format mp3 --voice-id Mizuki --text "$text" "$temp" 1>&2

## Output speech into standard output
cat "$temp"
